@startuml
title NS_ROAD_Update State Machine

state "TL_RED" as NS_RED
state "TL_YELLOW" as NS_YELLOW
state "TL_RED_YELLOW" as NS_RED_YELLOW
state "TL_GREEN" as NS_GREEN
state "TL_PEDESTRIAN" as NS_PEDESTRIAN

[*] --> NS_RED_YELLOW : Initial State

NS_RED_YELLOW --> NS_GREEN : Timer Expires (TLC_NS_RED_YELLOW_TIME_S)
NS_GREEN --> NS_YELLOW : Timer Expires (TLC_NS_GREEN_TIME_S)
NS_YELLOW --> NS_RED : Timer Expires (TLC_NS_YELLOW_TIME_S) AND Pedestrian Request = FALSE
NS_YELLOW --> NS_PEDESTRIAN : Timer Expires (TLC_NS_YELLOW_TIME_S) AND Pedestrian Request = TRUE
NS_RED --> NS_RED_YELLOW : Timer Expires (TLC_NS_RED_TIME_S)
NS_RED --> NS_PEDESTRIAN : Pedestrian Button Pressed
NS_PEDESTRIAN --> NS_RED : Timer Expires (TLC_PEDESTRIAN_TIME_S)

@enduml